\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Repro},
            pdfauthor={cvv},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Repro}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{cvv}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{9 March 2019}


\begin{document}
\maketitle

\section{The Most Damaging Weather Events in the United States in terms
of Fatality, Injuries, Property and Crop
Damages}\label{the-most-damaging-weather-events-in-the-united-states-in-terms-of-fatality-injuries-property-and-crop-damages}

\subsection{Synopsis}\label{synopsis}

This analysis explores the NOAA Storm Database which has the storm data
documenting severe weather events in United States, it's effects in
terms of population health and economic damages. It gives information on
events that happened, the number of injuries and fatalities that can be
assosiatied in those events, as well as damages of property and crops in
dollar value.

\subsection{Data Processing}\label{data-processing}

\subsubsection{\texorpdfstring{1. Read raw data file
``repdata\_data\_StormData.csv.bz2''?}{1. Read raw data file repdata\_data\_StormData.csv.bz2?}}\label{read-raw-data-file-repdata_data_stormdata.csv.bz2}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rawdata <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"repdata_data_StormData.csv.bz2"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(}\StringTok{"dplyr"}\NormalTok{)}
\NormalTok{data <-}\StringTok{ }\NormalTok{rawdata }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{ (EVTYPE, FATALITIES, INJURIES, PROPDMG,PROPDMGEXP,CROPDMG,CROPDMGEXP)}
\end{Highlighting}
\end{Shaded}

We only get the relevant measures. The event type, number of fatalities,
number of injuries, property damages value \& scale, and finally crop
damages value \& scale.

\subsubsection{2. Summarise Fatalities and Injuries by
event}\label{summarise-fatalities-and-injuries-by-event}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{popHealthByEvent <-}\StringTok{ }
\StringTok{  }\NormalTok{data }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{group_by}\NormalTok{(EVTYPE)  }\OperatorTok{%>%}\StringTok{ }
\StringTok{      }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{Ocurrances =} \KeywordTok{n}\NormalTok{(), }
                \DataTypeTok{Fatalities =} \KeywordTok{sum}\NormalTok{(}\KeywordTok{coalesce}\NormalTok{(FATALITIES,}\DecValTok{0}\NormalTok{)), }
                \DataTypeTok{Injuries =} \KeywordTok{sum}\NormalTok{(}\KeywordTok{coalesce}\NormalTok{(INJURIES,}\DecValTok{0}\NormalTok{)),}
                \DataTypeTok{Fatalities_and_Injuries =}\NormalTok{ Fatalities }\OperatorTok{+}\StringTok{ }\NormalTok{Injuries}
\NormalTok{                ) }\OperatorTok{%>%}\StringTok{ }
\StringTok{        }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(Fatalities_and_Injuries))  }\OperatorTok{%>%}\StringTok{ }
\StringTok{          }\KeywordTok{top_n}\NormalTok{(}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{3. Summarise Property and Crop Damages by type of
event}\label{summarise-property-and-crop-damages-by-type-of-event}

Property and Crop Damages in estimated dollar value can indicate
economic consequences of these events. - For the property damages, we
use PROPDMG column which contains the amount of the damages, and
PROPDMGEXP which specifies scale/exponent used (e.g.~B for Billions). -
For the crop damages, we use CROPDMG which has the amount, and
CROPDMGEXP which specifies scale/exponent used.

Mentioned in
\href{https://d396qusza40orc.cloudfront.net/repdata\%2Fpeer2_doc\%2Fpd01016005curr.pdf}{National
Weather Service Storm Data Documentation} item 2.7 Damage, on page 12.

\begin{quote}
Estimates should be rounded to three significant digits, followed by an
alphabetical character signifying the magnitude of the number, i.e.,
1.55B for \$1,550,000,000. Alphabetical characters used to signify
magnitude include ``K'' for thousands, ``M'' for millions, and ``B'' for
billions. If additional precision is available, it may be provided in
the narrative part of the entry.
\end{quote}

\begin{itemize}
\item
  Here are the PROPDMGEXP scales/symbols used: K, M, , B, m, +, 0, 5, 6,
  ?, 4, 2, 3, h, 7, H, -, 1, 8
\item
  Here are the CROPDMGEXP scales/symbols used: , M, K, m, B, ?, 0, k, 2
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{damages <-}\StringTok{ }
\StringTok{  }\NormalTok{data }\OperatorTok{%>%}\StringTok{ }
\StringTok{      }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{PROPDMG =} \KeywordTok{coalesce}\NormalTok{(PROPDMG,}\DecValTok{0}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{      }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{CROPDMG =} \KeywordTok{coalesce}\NormalTok{(CROPDMG,}\DecValTok{0}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{      }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{prop_multiplier =} \KeywordTok{case_when}\NormalTok{(}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ 'B'} \OperatorTok{|}\StringTok{ }\NormalTok{PROPDMGEXP }\OperatorTok{==}\StringTok{ 'b'} \OperatorTok{~}\StringTok{ }\DecValTok{1000000000}\NormalTok{,}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ 'M'} \OperatorTok{|}\StringTok{ }\NormalTok{PROPDMGEXP }\OperatorTok{==}\StringTok{ 'm'} \OperatorTok{~}\StringTok{ }\DecValTok{1000000}\NormalTok{,}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ 'K'} \OperatorTok{|}\StringTok{ }\NormalTok{PROPDMGEXP }\OperatorTok{==}\StringTok{ 'k'} \OperatorTok{~}\StringTok{ }\DecValTok{1000}\NormalTok{,}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ 'H'} \OperatorTok{|}\StringTok{ }\NormalTok{PROPDMGEXP }\OperatorTok{==}\StringTok{ 'h'} \OperatorTok{~}\StringTok{ }\DecValTok{100}\NormalTok{,}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ '1'} \OperatorTok{~}\StringTok{ }\DecValTok{10}\OperatorTok{*}\DecValTok{1}\NormalTok{,}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ '2'} \OperatorTok{~}\StringTok{ }\DecValTok{10}\OperatorTok{*}\DecValTok{2}\NormalTok{,}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ '3'} \OperatorTok{~}\StringTok{ }\DecValTok{10}\OperatorTok{*}\DecValTok{3}\NormalTok{,}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ '4'} \OperatorTok{~}\StringTok{ }\DecValTok{10}\OperatorTok{*}\DecValTok{4}\NormalTok{,}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ '5'} \OperatorTok{~}\StringTok{ }\DecValTok{10}\OperatorTok{*}\DecValTok{5}\NormalTok{,}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ '6'} \OperatorTok{~}\StringTok{ }\DecValTok{10}\OperatorTok{*}\DecValTok{6}\NormalTok{,}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ '7'} \OperatorTok{~}\StringTok{ }\DecValTok{10}\OperatorTok{*}\DecValTok{7}\NormalTok{,}
\NormalTok{                                    PROPDMGEXP }\OperatorTok{==}\StringTok{ '8'} \OperatorTok{~}\StringTok{ }\DecValTok{10}\OperatorTok{*}\DecValTok{8}\NormalTok{,}
                                    \OtherTok{TRUE} \OperatorTok{~}\StringTok{ }\DecValTok{1}\NormalTok{) }\CommentTok{# else, just use the value as it is}
\NormalTok{             ) }\OperatorTok{%>%}\StringTok{ }
\StringTok{      }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{prop_value =}\NormalTok{ prop_multiplier }\OperatorTok{*}\StringTok{ }\NormalTok{PROPDMG) }\OperatorTok{%>%}\StringTok{ }
\StringTok{      }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{crop_multiplier =} \KeywordTok{case_when}\NormalTok{(}
\NormalTok{                                    CROPDMGEXP }\OperatorTok{==}\StringTok{ 'B'} \OperatorTok{|}\StringTok{ }\NormalTok{CROPDMGEXP }\OperatorTok{==}\StringTok{ 'b'} \OperatorTok{~}\StringTok{ }\DecValTok{1000000000}\NormalTok{,}
\NormalTok{                                    CROPDMGEXP }\OperatorTok{==}\StringTok{ 'M'} \OperatorTok{|}\StringTok{ }\NormalTok{CROPDMGEXP }\OperatorTok{==}\StringTok{ 'm'} \OperatorTok{~}\StringTok{ }\DecValTok{1000000}\NormalTok{,}
\NormalTok{                                    CROPDMGEXP }\OperatorTok{==}\StringTok{ 'K'} \OperatorTok{|}\StringTok{ }\NormalTok{CROPDMGEXP }\OperatorTok{==}\StringTok{ 'k'} \OperatorTok{~}\StringTok{ }\DecValTok{1000}\NormalTok{,}
\NormalTok{                                    CROPDMGEXP }\OperatorTok{==}\StringTok{ 'H'} \OperatorTok{|}\StringTok{ }\NormalTok{CROPDMGEXP }\OperatorTok{==}\StringTok{ 'h'} \OperatorTok{~}\StringTok{ }\DecValTok{100}\NormalTok{,}
\NormalTok{                                    CROPDMGEXP }\OperatorTok{==}\StringTok{ '1'} \OperatorTok{~}\StringTok{ }\DecValTok{10}\OperatorTok{*}\DecValTok{1}\NormalTok{,}
\NormalTok{                                    CROPDMGEXP }\OperatorTok{==}\StringTok{ '2'} \OperatorTok{~}\StringTok{ }\DecValTok{10}\OperatorTok{*}\DecValTok{2}\NormalTok{,}
\NormalTok{                                    CROPDMGEXP }\OperatorTok{==}\StringTok{ '3'} \OperatorTok{~}\StringTok{ }\DecValTok{10}\OperatorTok{*}\DecValTok{3}\NormalTok{,}
                                    \OtherTok{TRUE} \OperatorTok{~}\StringTok{ }\DecValTok{1}\NormalTok{) }\CommentTok{# else, just use the value as it is}
\NormalTok{             ) }\OperatorTok{%>%}\StringTok{ }
\StringTok{      }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{crop_value =}\NormalTok{ crop_multiplier }\OperatorTok{*}\StringTok{ }\NormalTok{CROPDMG)  }\OperatorTok{%>%}\StringTok{ }
\StringTok{      }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{damage_value =}\NormalTok{ prop_value }\OperatorTok{+}\StringTok{ }\NormalTok{crop_value)}

\NormalTok{damagesByEvent <-}\StringTok{ }
\StringTok{  }\NormalTok{damages }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{group_by}\NormalTok{(EVTYPE)  }\OperatorTok{%>%}\StringTok{ }
\StringTok{      }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{prop_value =} \KeywordTok{sum}\NormalTok{(prop_value), }\DataTypeTok{crop_value =} \KeywordTok{sum}\NormalTok{(crop_value)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{        }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{total_value =}\NormalTok{ prop_value }\OperatorTok{+}\StringTok{ }\NormalTok{crop_value) }\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(total_value))  }\OperatorTok{%>%}\StringTok{ }
\StringTok{            }\KeywordTok{top_n}\NormalTok{(}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Results}\label{results}

\paragraph{1. This table summarises the events and its negative effect
in population
health.}\label{this-table-summarises-the-events-and-its-negative-effect-in-population-health.}

\begin{verbatim}
## # A tibble: 10 x 5
##    EVTYPE            Ocurrances Fatalities Injuries Fatalities_and_Injuries
##    <fct>                  <int>      <dbl>    <dbl>                   <dbl>
##  1 TORNADO                60652       5633    91346                   96979
##  2 EXCESSIVE HEAT          1678       1903     6525                    8428
##  3 TSTM WIND             219940        504     6957                    7461
##  4 FLOOD                  25326        470     6789                    7259
##  5 LIGHTNING              15754        816     5230                    6046
##  6 HEAT                     767        937     2100                    3037
##  7 FLASH FLOOD            54277        978     1777                    2755
##  8 ICE STORM               2006         89     1975                    2064
##  9 THUNDERSTORM WIND      82563        133     1488                    1621
## 10 WINTER STORM           11433        206     1321                    1527
\end{verbatim}

The top three events that caused the most number of both injuries and
fatalities are \textbf{tornado (96979), excessive heat (8428), and tstm
wind (7461)}. While tstm wind has more occurrances, tornado still tops
for the damage in life

\paragraph{2. This table summarises the events and its damages in dollar
value.}\label{this-table-summarises-the-events-and-its-damages-in-dollar-value.}

\begin{verbatim}
## # A tibble: 10 x 4
##    EVTYPE               prop_value  crop_value   total_value
##    <fct>                     <dbl>       <dbl>         <dbl>
##  1 FLOOD             144657709807   5661968450 150319678257 
##  2 HURRICANE/TYPHOON  69305840000   2607872800  71913712800 
##  3 TORNADO            56937165786.   414953270  57352119056.
##  4 STORM SURGE        43323536000         5000  43323541000 
##  5 HAIL               15732269013.  3025954473  18758223486.
##  6 FLASH FLOOD        16140817746.  1421317100  17562134846.
##  7 DROUGHT             1046106000  13972566000  15018672000 
##  8 HURRICANE          11868319010   2741910000  14610229010 
##  9 RIVER FLOOD         5118945500   5029459000  10148404500 
## 10 ICE STORM           3944927860   5022113500   8967041360
\end{verbatim}

The events with the most damages are Flood at \$150 Billion, then
Hurricane/Typhoon at \$71 Billion, and Tornado at \$57 Billion.

\paragraph{3. The plots below show the damages in population health and
properties}\label{the-plots-below-show-the-damages-in-population-health-and-properties}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{require}\NormalTok{(gridExtra)}
\NormalTok{plot1 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{popHealthByEvent, }
        \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{reorder}\NormalTok{(EVTYPE, }\OperatorTok{-}\NormalTok{Fatalities_and_Injuries), }\DataTypeTok{y=}\NormalTok{Fatalities_and_Injuries)) }\OperatorTok{+}\StringTok{ }
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{        }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{90}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Most Harmful Events to Population Health in US"}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Event"}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Total Fatalities & Injuries"}\NormalTok{)}

\NormalTok{damagesByEvent}\OperatorTok{$}\NormalTok{total_value <-}\StringTok{ }\NormalTok{damagesByEvent}\OperatorTok{$}\NormalTok{total_value }\OperatorTok{/}\StringTok{ }\DecValTok{1000000000} \CommentTok{#convert to billions}
\NormalTok{plot2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{damagesByEvent, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{reorder}\NormalTok{(EVTYPE, }\OperatorTok{-}\NormalTok{total_value), }\DataTypeTok{y=}\NormalTok{damagesByEvent}\OperatorTok{$}\NormalTok{total_value)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{90}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Most Damaging Events in US"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Event"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Total Damages (in Billion $)"}\NormalTok{)}

\KeywordTok{grid.arrange}\NormalTok{(plot1, plot2, }\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Repro_files/figure-latex/unnamed-chunk-7-1.pdf}

\subsubsection{In summary, the most damaging type of event in terms of
injuries and fatalities is Tornado, which caused 91346 injuries and
60652 casualties. Moreover, the Flood causes the most damages with a
total of \$150.3 Billion in properties (\$144.7B) and crops
(\$5.6M).}\label{in-summary-the-most-damaging-type-of-event-in-terms-of-injuries-and-fatalities-is-tornado-which-caused-91346-injuries-and-60652-casualties.-moreover-the-flood-causes-the-most-damages-with-a-total-of-150.3-billion-in-properties-144.7b-and-crops-5.6m.}


\end{document}
